---
version: '3'

services:
  database:
    image: postgres:12.2
    volumes:
    - ../django_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fragalysis
      POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  tests:
    image: ${STACK_NAMESPACE:-xchem}/fragalysis-stack:${STACK_TAG:-latest}
    command:
    - /code/wait-for-it.sh
    - database:5432
    - --
    - /bin/bash
    - /code/test_entry.sh
    volumes:
    - ../logs:/code/logs/
    - ../media:/code/media/
    environment:
      POSTGRESQL_DATABASE: frag
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: fragalysis
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: 5432
    ports:
    - "80:80"
    depends_on:
    - database
